<?php

/**
 * BaseDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $property_id
 * @property varchar $name
 * @property text $description
 * @property varchar $movie_url
 * @property boolean $has_photos
 * @property boolean $has_features
 * @property Property $Property
 * @property Doctrine_Collection $Photos
 * @property Doctrine_Collection $Features
 * 
 * @method integer             getPropertyId()   Returns the current record's "property_id" value
 * @method varchar             getName()         Returns the current record's "name" value
 * @method text                getDescription()  Returns the current record's "description" value
 * @method varchar             getMovieUrl()     Returns the current record's "movie_url" value
 * @method boolean             getHasPhotos()    Returns the current record's "has_photos" value
 * @method boolean             getHasFeatures()  Returns the current record's "has_features" value
 * @method Property            getProperty()     Returns the current record's "Property" value
 * @method Doctrine_Collection getPhotos()       Returns the current record's "Photos" collection
 * @method Doctrine_Collection getFeatures()     Returns the current record's "Features" collection
 * @method Detail              setPropertyId()   Sets the current record's "property_id" value
 * @method Detail              setName()         Sets the current record's "name" value
 * @method Detail              setDescription()  Sets the current record's "description" value
 * @method Detail              setMovieUrl()     Sets the current record's "movie_url" value
 * @method Detail              setHasPhotos()    Sets the current record's "has_photos" value
 * @method Detail              setHasFeatures()  Sets the current record's "has_features" value
 * @method Detail              setProperty()     Sets the current record's "Property" value
 * @method Detail              setPhotos()       Sets the current record's "Photos" collection
 * @method Detail              setFeatures()     Sets the current record's "Features" collection
 * 
 * @package    
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detail');
        $this->hasColumn('property_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('movie_url', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('has_photos', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('has_features', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Property', array(
             'local' => 'property_id',
             'foreign' => 'id'));

        $this->hasMany('Photo as Photos', array(
             'local' => 'id',
             'foreign' => 'detail_id'));

        $this->hasMany('Feature as Features', array(
             'local' => 'id',
             'foreign' => 'detail_id'));
    }
}