<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $detail_id
 * @property integer $property_id
 * @property boolean $is_main_photo
 * @property integer $views
 * @property Property $Property
 * @property Detail $Detail
 * 
 * @method integer  getDetailId()      Returns the current record's "detail_id" value
 * @method integer  getPropertyId()    Returns the current record's "property_id" value
 * @method boolean  getIsMainPhoto()   Returns the current record's "is_main_photo" value
 * @method integer  getViews()         Returns the current record's "views" value
 * @method Property getProperty()      Returns the current record's "Property" value
 * @method Detail   getDetail()        Returns the current record's "Detail" value
 * @method Photo    setDetailId()      Sets the current record's "detail_id" value
 * @method Photo    setPropertyId()    Sets the current record's "property_id" value
 * @method Photo    setIsMainPhoto()   Sets the current record's "is_main_photo" value
 * @method Photo    setViews()         Sets the current record's "views" value
 * @method Photo    setProperty()      Sets the current record's "Property" value
 * @method Photo    setDetail()        Sets the current record's "Detail" value
 * 
 * @package    
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('detail_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('property_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_main_photo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('views', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Property', array(
             'local' => 'property_id',
             'foreign' => 'id'));

        $this->hasOne('Detail', array(
             'local' => 'detail_id',
             'foreign' => 'id'));

        $photoable0 = new Doctrine_Template_Photoable();
        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'detail_id',
             ),
             ));
        $this->actAs($photoable0);
        $this->actAs($sortable0);
    }
}