# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [backend.css]

  javascripts:
    - jquery-1.4.2.min.js
    - backend
    - tiny_mce/tiny_mce.js
    - event.drag.js
    - event.drop.js
    - jquery.ui.core.js
    - jquery.ui.widget.js
    - jquery.ui.mouse.js
    - jquery.ui.draggable.js
    - jquery.ui.sortable.js

  has_layout:     true
  layout:         layout
