<?php

/**
 * Property
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Property extends BaseProperty
{

	public function __toString() { return $this->getFormattedAddress(); }

	public function getFormattedAddress() { return sprintf("%s, %s, %s %s", $this->getStreet(),
																   $this->getCity(), $this->getState(),
																   $this->getPostalCode()
																   ); }

	public function getMainPhoto() {
		return Doctrine::getTable('Photo')->
					createQuery('q')->
					where('property_id = ?', $this->getId())->
					andWhere('is_main_photo = ?', true)->
					execute()->
					getFirst();
	}

	public function getPhotos()
	{
		return Doctrine::getTable('Photo')->
					createQuery('p')->
					where('p.property_id = ?', $this->getId())->
					orderBy('p.position')->
					execute();
	}

}
