generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Property
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          property
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [user, formatted_address, tagline, price]
      filter:
        class:   false
      form:    ~
      edit:    ~
      new:     ~
